<?php

namespace Jovian\Venusian\GTK\Input;

use Surface\Contracts\HumanInput\Key;

/**
 * Linux evdev key codes (`linux/input-event-codes.h`) → Surface keys. Layout
 * independent. GTK's hardware keycode is this code + 8 on X11 and Wayland;
 * the caller subtracts. Anything unmapped is Key::UNKNOWN.
 */
final class EvdevKeyMap
{
    public static function key(int $evdev_code): Key
    {
        return match (true) {
            $evdev_code >= 2 && $evdev_code <= 10 => Key::from('digit_'.($evdev_code - 1)),
            $evdev_code >= 59 && $evdev_code <= 68 => Key::from('f'.($evdev_code - 58)),
            default => match ($evdev_code) {
                1 => Key::ESCAPE,
                11 => Key::DIGIT_0,
                12 => Key::MINUS,
                13 => Key::EQUALS,
                14 => Key::BACKSPACE,
                15 => Key::TAB,
                16 => Key::Q,
                17 => Key::W,
                18 => Key::E,
                19 => Key::R,
                20 => Key::T,
                21 => Key::Y,
                22 => Key::U,
                23 => Key::I,
                24 => Key::O,
                25 => Key::P,
                26 => Key::LEFT_BRACKET,
                27 => Key::RIGHT_BRACKET,
                28 => Key::ENTER,
                29 => Key::LEFT_CTRL,
                30 => Key::A,
                31 => Key::S,
                32 => Key::D,
                33 => Key::F,
                34 => Key::G,
                35 => Key::H,
                36 => Key::J,
                37 => Key::K,
                38 => Key::L,
                39 => Key::SEMICOLON,
                40 => Key::APOSTROPHE,
                41 => Key::GRAVE,
                42 => Key::LEFT_SHIFT,
                43 => Key::BACKSLASH,
                44 => Key::Z,
                45 => Key::X,
                46 => Key::C,
                47 => Key::V,
                48 => Key::B,
                49 => Key::N,
                50 => Key::M,
                51 => Key::COMMA,
                52 => Key::PERIOD,
                53 => Key::SLASH,
                54 => Key::RIGHT_SHIFT,
                55 => Key::NUMPAD_MULTIPLY,
                56 => Key::LEFT_ALT,
                57 => Key::SPACE,
                58 => Key::CAPS_LOCK,
                69 => Key::NUM_LOCK,
                70 => Key::SCROLL_LOCK,
                71 => Key::NUMPAD_7,
                72 => Key::NUMPAD_8,
                73 => Key::NUMPAD_9,
                74 => Key::NUMPAD_MINUS,
                75 => Key::NUMPAD_4,
                76 => Key::NUMPAD_5,
                77 => Key::NUMPAD_6,
                78 => Key::NUMPAD_PLUS,
                79 => Key::NUMPAD_1,
                80 => Key::NUMPAD_2,
                81 => Key::NUMPAD_3,
                82 => Key::NUMPAD_0,
                83 => Key::NUMPAD_PERIOD,
                87 => Key::F11,
                88 => Key::F12,
                96 => Key::NUMPAD_ENTER,
                97 => Key::RIGHT_CTRL,
                98 => Key::NUMPAD_DIVIDE,
                99 => Key::PRINT_SCREEN,
                100 => Key::RIGHT_ALT,
                102 => Key::HOME,
                103 => Key::UP,
                104 => Key::PAGE_UP,
                105 => Key::LEFT,
                106 => Key::RIGHT,
                107 => Key::END,
                108 => Key::DOWN,
                109 => Key::PAGE_DOWN,
                110 => Key::INSERT,
                111 => Key::DELETE,
                117 => Key::NUMPAD_EQUALS,
                119 => Key::PAUSE,
                125 => Key::LEFT_META,
                126 => Key::RIGHT_META,
                127 => Key::MENU,
                default => Key::UNKNOWN,
            },
        };
    }
}
